name: estudo
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^6.0.1
  provider: ^6.0.5
  localization: ^2.1.0
  flutter_launcher_icons: "^0.13.1"
  shared_preferences: ^2.2.0
  gif: ^2.2.0
  http: ^1.1.0
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  image_picker: ^1.0.1
  path_provider: ^2.0.15
  path: ^1.8.3
  curved_navigation_bar: ^1.0.3

  flutter_localizations:
    sdk: flutter
  cloud_firestore: ^4.8.4
  firebase_storage: ^11.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "lib/assets/images/SNAP_LOGO.PNG.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "lib/assets/images/SNAP_LOGO.PNG.png"
  
flutter:
  uses-material-design: true

  assets:
    - lib/assets/
    - lib/assets/i18n/
    - lib/assets/images/
    - lib/assets/fonts/
 
  fonts:
    - family: Lato
      fonts:
        - asset: lib/assets/fonts/Lato-Regular.ttf
        - asset: lib/assets/fonts/Lato-Bold.ttf
          weight: 700